package com.Enum;

public enum AdminOption {
    ADD_COLLEGE,VIEW_COLLEGE,VIEW_STUDENTS,VIEW_ALL_COLLEGES,GENERATE_CUTOFF,GENERATE_RANDOM_NO,GENERATE_RANK,ALLOCATE_SEAT,VIEW_FINAL_ALLOTMENTS,LOGOUT
}
